# Generated by Django 5.1.4 on 2024-12-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='fim_expediente',
        ),
        migrations.AddField(
            model_name='expediente',
            name='horas_expediente',
            field=models.IntegerField(default=8),
        ),
    ]
