# Generated by Django 5.1.4 on 2025-01-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_remove_expediente_fim_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='ponto.empresa'),
        ),
    ]
