# Generated by Django 5.1.4 on 2025-01-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='ponto.funcionario'),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto', to='ponto.funcionario'),
        ),
    ]
