# Generated by Django 5.1.4 on 2025-01-02 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_alter_expediente_funcionario_alter_ponto_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
